import Accordion from "@/app/components/ui/Accordion";
import Link from "next/link";

export default function FAQ() {
  const faqs = [
    {
      id: "1",
      title: "What image formats are supported?",
      content:
        "Prompt Lab supports JPG, PNG, and WebP formats. Each image can be up to 5 MB. Simply drag and drop or click to upload.",
    },
    {
      id: "2",
      title: "How long does the analysis take?",
      content:
        "Most images are analyzed in under 2 seconds. Advanced AI models sometimes take up to 5 seconds, but it's still very fast compared to manual prompt writing.",
    },
    {
      id: "3",
      title: "Can I use generated prompts commercially?",
      content:
        "Yes! Prompts generated by Prompt Lab are yours to use. However, generated images created with those prompts depend on the specific AI art generator's terms of service.",
    },
    {
      id: "4",
      title: "Do you store my images?",
      content:
        "No, we don't store your images on our servers. Images are processed in memory and immediately discarded after analysis. Your privacy is important to us.",
    },
    {
      id: "5",
      title: "Can I generate prompts for any image style?",
      content:
        "Yes! Our AI works with any image — photographs, paintings, sketches, abstract art, etc. It generates prompts optimized for Midjourney, Stable Diffusion, and DALL-E.",
    },
    {
      id: "6",
      title: "What's the difference between plans?",
      content:
        "Free plan includes 5 generations/month with basic features. Pro plan offers unlimited generations, advanced optimization, and priority support. Enterprise is for teams with custom needs.",
    },
    {
      id: "7",
      title: "Can I get a refund?",
      content:
        "Yes, we offer a 7-day money-back guarantee on Pro subscriptions. No questions asked. If you're not satisfied, we'll refund you immediately.",
    },
    {
      id: "8",
      title: "Is there an API?",
      content:
        "API access is available on Enterprise plans. It allows you to integrate Prompt Lab into your own applications. Contact sales for details.",
    },
  ];

  return (
    <div className="bg-canvas">
      {/* Header */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center">
        <h1 className="text-4xl sm:text-5xl font-semibold text-ink tracking-tight mb-4">
          Frequently Asked Questions
        </h1>
        <p className="text-xl text-steel">
          Everything you need to know about Prompt Lab.
        </p>
      </div>

      {/* Accordion */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
        <Accordion items={faqs} />
      </div>

      {/* Still have questions */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
        <div className="bg-surface rounded-[12px] p-10 text-center">
          <h2 className="text-xl font-semibold text-ink mb-2">Still have questions?</h2>
          <p className="text-steel text-base mb-5">
            We&apos;re here to help. Reach out to our support team anytime.
          </p>
          <Link
            href="mailto:support@promptlab.com"
            className="inline-block px-[18px] py-[10px] bg-primary hover:bg-primary-pressed text-white text-sm font-medium rounded-[8px] transition-colors"
          >
            Contact Support
          </Link>
        </div>
      </div>
    </div>
  );
}
